name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 6 * * *"  # Kjører hver dag kl 06:00 UTC (08:00 norsk tid)
  workflow_dispatch:      # Lar deg starte manuelt fra Actions-fanen

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase REST API
        run: |
          curl -s "${SUPABASE_URL}/rest/v1/blogg_tekst_renset?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}"
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
