name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 6,18 * * *"   # Kjør kl 06:00 og 18:00 UTC (08:00 og 20:00 norsk tid)
  workflow_dispatch:           # Manuell kjøring fra Actions

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq (for logging)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ping Supabase (hent 1 rad)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Kaller: ${SUPABASE_URL}/rest/v1/blogg_tekst_renset?select=id&limit=1"
          RESPONSE=$(curl -s -w "\n%{http_code}" \
            "${SUPABASE_URL}/rest/v1/blogg_tekst_renset?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}")
          
          # Splitt ut body og status
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1)
          BODY=$(echo "$RESPONSE" | sed '$d')

          echo "HTTP status: $HTTP_STATUS"
          echo "Rått svar:"
          echo "$BODY"

          # Hvis JSON, vis antall elementer
          if echo "$BODY" | jq . >/dev/null 2>&1; then
            COUNT=$(echo "$BODY" | jq 'length')
            echo "Antall elementer i JSON: $COUNT"
          fi

          # Fail hvis status er 4xx/5xx
          if [ "$HTTP_STATUS" -ge 400 ]; then
            echo "Ping feilet"; exit 1
          fi
