name: Keep Supabase Alive

on:
  schedule:
    - cron: "0 6 */5 * *"   # hver 5. dag kl 06:00 UTC
  workflow_dispatch:         # manuell kjøring

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase
        run: |
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
            "${SUPABASE_URL}/rest/v1/blogg_tekst_renset?select=id&limit=1" \
            -H "apikey: ${SUPABASE_ANON_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_ANON_KEY}")
          echo "HTTP status: $STATUS"
          if [ "$STATUS" -ge 400 ] || [ -z "$STATUS" ]; then
            echo "Ping feilet"; exit 1
          fi
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
